CREATE TABLE Deweloperzy (
    ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nazwa VARCHAR2(64) NOT NULL,
    CONSTRAINT PK_Deweloperzy PRIMARY KEY(ID)
);

CREATE TABLE Gatunki (
    nazwa VARCHAR2(64) CONSTRAINT PK_Gatunki PRIMARY KEY
);

CREATE TABLE Platformy (
    nazwa VARCHAR2(64) CONSTRAINT PK_Platformy PRIMARY KEY
);

CREATE TABLE Franczyzy (
    nazwa VARCHAR2(64) CONSTRAINT PK_Franczyzy PRIMARY KEY
);

CREATE TABLE Gry (
    ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tytul VARCHAR2(128) NOT NULL,
    data_wydania DATE DEFAULT CURRENT_DATE NOT NULL,
    ograniczenie_wiekowe INTEGER NOT NULL CONSTRAINT Check_Gry_Ograniczenie_Wiekowe CHECK (ograniczenie_wiekowe IN (3, 7, 12, 16, 18)),
    okladka VARCHAR2(256) DEFAULT 'img/boxart/default.png' NULL,
    opis VARCHAR2(1024) DEFAULT 'Brak opisu.' NULL,
    deweloper INTEGER NULL CONSTRAINT FK_Gry_Deweloper REFERENCES Deweloperzy(ID) ON DELETE SET NULL,
    franczyza VARCHAR2(64) NULL CONSTRAINT FK_Gry_Franczyza REFERENCES Franczyzy(nazwa) ON DELETE SET NULL,
    dodatek NUMBER(1) NOT NULL CONSTRAINT Check_Gry_Dodatek_Bool CHECK (dodatek IN (0, 1)),
    gra_podstawowa INTEGER NULL CONSTRAINT FK_Dodatki_Gra_Podstawowa REFERENCES Gry(ID) ON DELETE CASCADE,
    CONSTRAINT PK_Gry PRIMARY KEY(ID),
    CONSTRAINT Check_Dodatek CHECK ((dodatek = 1 AND gra_podstawowa IS NOT NULL) OR (dodatek = 0 AND gra_podstawowa IS NULL))
);

CREATE TABLE Gry_Gatunki (
    ID_Gry INTEGER CONSTRAINT FK_Gry_Gatunki_Gra REFERENCES Gry(ID) ON DELETE CASCADE,
    nazwa_gatunku VARCHAR2(64) CONSTRAINT FK_Gry_Gatunki_Gatunek REFERENCES Gatunki(nazwa) ON DELETE CASCADE,
    CONSTRAINT PK_Gry_Gatunki PRIMARY KEY (ID_Gry, nazwa_gatunku)
);

CREATE TABLE Gry_Platformy (
    ID_Gry INTEGER CONSTRAINT FK_Gry_Platformy_Gra REFERENCES Gry(ID) ON DELETE CASCADE,
    nazwa_platformy VARCHAR2(64) CONSTRAINT FK_Gry_Platformy_Platforma REFERENCES Platformy(nazwa) ON DELETE CASCADE,
    CONSTRAINT PK_Gry_Platformy PRIMARY KEY (ID_Gry, nazwa_platformy)
);

CREATE TABLE Uzytkownicy (
    ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nazwa VARCHAR2(64) NOT NULL CONSTRAINT UK_Uzytkownicy_Nazwa UNIQUE,
    email VARCHAR2(128) NOT NULL CONSTRAINT UK_Uzytkownicy_Email UNIQUE,
    haslo VARCHAR2(128) NOT NULL,
    data_zalozenia DATE DEFAULT CURRENT_DATE NOT NULL,
    zdjecie_profilowe VARCHAR2(128) DEFAULT 'img/avatars/default.png' NULL,
    opis VARCHAR2(512) DEFAULT 'Brak opisu.' NULL,
    administrator NUMBER(1) NOT NULL CONSTRAINT Check_Uzytkownicy_Administrator_Bool CHECK (administrator IN (0, 1)),
    CONSTRAINT PK_Uzytkownicy PRIMARY KEY (ID)
);

CREATE TABLE Znajomosci (
    ID_Uzytkownik1 INTEGER NOT NULL CONSTRAINT FK_Znajomosci_Uzytkownik1 REFERENCES Uzytkownicy(ID) ON DELETE CASCADE,
    ID_Uzytkownik2 INTEGER NOT NULL CONSTRAINT FK_Znajomosci_Uzytkownik2 REFERENCES Uzytkownicy(ID) ON DELETE CASCADE,
    CONSTRAINT PK_Znajomosci PRIMARY KEY (ID_Uzytkownik1, ID_Uzytkownik2),
    CONSTRAINT Check_Znajomosci_ID CHECK (ID_Uzytkownik1 < ID_Uzytkownik2)
);

CREATE TABLE Wpisy (
    ID_Uzytkownika INTEGER NOT NULL CONSTRAINT FK_Wpisy_Uzytkownik REFERENCES Uzytkownicy(ID) ON DELETE CASCADE,
    ID_Gry INTEGER NOT NULL CONSTRAINT FK_Wpisy_Gra REFERENCES Gry(ID) ON DELETE CASCADE,
    w_trakcie NUMBER(1) NOT NULL CONSTRAINT Check_Wpisy_WTrakcie_Bool CHECK (w_trakcie IN (0, 1)),
    czy_ukonczona NUMBER(1) NOT NULL CONSTRAINT Check_Wpisy_Ukonczenie_Bool CHECK (czy_ukonczona IN (0, 1)),
    sto_procent NUMBER(1) NOT NULL CONSTRAINT Check_Wpisy_Sto_Bool CHECK (sto_procent IN (0, 1)),
    czy_ulubiona NUMBER(1) NOT NULL CONSTRAINT Check_Wpisy_Ulubiona_Bool CHECK (czy_ulubiona IN (0, 1)),
    czas NUMBER(7, 2) NULL, 
    CONSTRAINT PK_Wpisy PRIMARY KEY (ID_Uzytkownika, ID_Gry)
);

CREATE TABLE Recenzje (
    ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ocena INTEGER NOT NULL CONSTRAINT Check_Recenzje_Ocena CHECK (ocena >= 1 AND ocena <= 10),
    data_wystawienia TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    komentarz VARCHAR2(512) NULL,
    ID_Uzytkownika INTEGER NOT NULL CONSTRAINT FK_Recenzje_Uzytkownik REFERENCES Uzytkownicy(ID) ON DELETE CASCADE,
    ID_Gry INTEGER NOT NULL CONSTRAINT FK_Recenzje_Gra REFERENCES Gry(ID) ON DELETE CASCADE
);

CREATE TABLE Listy (
    ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nazwa VARCHAR2(64) NOT NULL,
    data_utworzenia TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    opis VARCHAR2(512) DEFAULT 'Brak opisu.' NULL,
    ID_Uzytkownika INTEGER NOT NULL CONSTRAINT FK_Listy_Uzytkownik REFERENCES Uzytkownicy(ID) ON DELETE CASCADE,
    CONSTRAINT PK_Listy PRIMARY KEY (ID)
);

CREATE TABLE Gry_w_liscie (
    ID_Gry INTEGER NOT NULL CONSTRAINT FK_Gry_Listy_Gra REFERENCES Gry(ID) ON DELETE CASCADE,
    ID_Listy INTEGER NOT NULL CONSTRAINT FK_Gry_Listy_Lista REFERENCES Listy(ID) ON DELETE CASCADE,
    data_dodania TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_Gry_w_Liscie PRIMARY KEY (ID_Gry, ID_Listy)
);